### ISSUE TITLE
[relay] Kick/mode war detection

### ISSUE THREAD

**Issue by jlu5** [jlu5/PyLink#23]
There should be [some sort of cache](https://pypi.python.org/pypi/expiringdict/1.1.2) that tracks the amount of kicks/modes/kills sent to a PyLink client to X per Y seconds. If the limit is reached, ~~it should either squit (in the event of kills)~~ (done in https://github.com/jlu5/PyLink/commit/0bb54d88e05431549cba39b0e172a70980ee727d), or ~~part the client from the channel~~ somehow stop relaying in the case of mode or kick wars. As far as I'm concerned, atheme services already does this with kills.

~~For PyLink-Relay, this would allow for behaviour quite similar to Janus' CLAIM: but instead of flooding a channel when services start applying DEFCON modes or killing over session limits, it will just delink the problematic networks in question~~.

edit 2018-02-27: This old issue needs more thought on what would be the best mitigation method. Preferably any workarounds will not introduce visible desyncs affecting more than just the problematic client(s).

edit 2019-05-09: Let's just use a hook (RELAY_CLAIM_BOUNCE) and a handler with a cache. Once we hit a limit, stop relaying the mode or kick - similarly to how we treat U-Lines in Relay.

**Comment by GLolol** [comment]
Debating moving this into core, so it can protect the PyLink client too from kill/kick wars. There should be a global kick/kill count that is incremented by both the core (when PyLink client is hit) and by relay (when a relay client is hit).

**Comment by siniStar7boy** [comment]
👍🏻
