### ISSUE TITLE
TOPIC changes should be handled using TS-rules instead of blindly accepted

### ISSUE THREAD

**Issue by jlu5** [jlu5/PyLink#277]
I put this off before because it wasn't as important as getting MODE handling right, but it'd be useful for things like #127.

**Comment by cooper** [comment]
Topic acceptance is inconsistent across IRCds.

## TS6
TOPIC is used for real-time topic changes. There are three commands to burst a topic: TB and ETB, plus TBURST which I know nothing about and think only hybrid still uses.

**TB** (capab: TB) is always used during the initial burst. It does not include the channel TS, only the topic TS. The command will overwrite the current topic if EITHER of these conditions is met:
* There was no topic stored already.
* The incoming topic TS is older (lower) than the stored one.

**ETB** (capab: EOPMOD) is an extended version. Unlike TB, it DOES include a channel TS parameter in addition to the topic TS. Its primary advantage over TB is that it can force a topic change even if the topicTS is newer (greater) than the stored one. It is also capable of modifying the topic TS without changing the text. The command will overwrite the current topic if ANY of these conditions are met:
* There was no topic stored already.
* The incoming channel TS is older (lower) than the stored one. This may be zero to force the topic change. Note that ETB should never unset modes or change the stored channel TS.
* The incoming channel TS is equal to the stored one AND the incoming topic TS is newer (greater) than the stored one. This means that, unlike TB, ETB will preserve the NEWEST topic, as long as the channel TS is equal.

ETB is used mostly for services and may not need to be implemented in PyLink. It is forwarded to servers without EOPMOD as TB when possible.

## InspIRCd

More complicated. It uses **FTOPIC** for both bursting and real-time changing of topics. It works like this, in this precedence:
* If the incoming channel TS is newer (greater) than the stored one, ignore the message.
* If the channel has EVER had a topic before, and the incoming topic TS is older (lower) than the stored one, ignore the message.
    * This means that the newest topic is preserved, opposite of TS6.
    * Note that InspIRCd stores and bursts topic info even if the topic has no length (i.e., when the server tells users that no topic is set). This means that a topic TS is stored even for an empty topic.
* If the incoming topic is a "smaller" version of the stored one, ignore the message.
    * Example: stored topic is "abc" and incoming topic is "ab" – ignored this.
    * This also effectively ignores empty topics when a topic with length is currently stored. However, if the stored topic and the incoming topic are both empty, the metadata should be accepted.
* If the incoming "set by" (OR if omitted, the full mask of the source of the FTOPIC message) parameter is equal to the stored "set by" data, ignore the message.
    * This is the final check. If this is not equal, the new topic is accepted.
* OK, it somehow survived all of these elaborate checks. Accept the topic.
