### ISSUE TITLE
Twitter Relay

### ISSUE THREAD

**Issue by ThePowerPig** [jlu5/PyLink#342]
Add a relay feature to relay twitter feeds to a specified IRC channel.  Names of the twitter accounts would become users on the channel.  Each name the twitter account is following would be a nickname on the IRC channel.  Also add the option to have the relay just be a 1 way relay from twitter to IRC if the user does not want to relay back to twitter.

**Comment by GLolol** [comment]
I was just thinking of a Twitter announcer but, but okay... There would have to be some way of managing Twitter accounts if relaying back is intended, but I'm not sure such a system would be secure.

Relay doesn't really support transports that don't behave like IRC connections (IRC objects with protocol modules attached), so this would probably be a separate plugin.
