### ISSUE TITLE
PyLink is disconnecting from servers with various socket errors, primarily SSL-related

### ISSUE THREAD

**Issue by Techman** [jlu5/PyLink#463]
I've been encountering this for a while on my box. It's running Ubuntu 16.04 LTS, x64. Throughout my time using the software, I've come across various kinds of socket errors.

* [ERROR] (nc) Disconnected from IRC: SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)
* [ERROR] (ttx) Disconnected from IRC: BlockingIOError: [Errno 11] Resource temporarily unavailable
* [ERROR] (ttx) Disconnected from IRC: ConnectionResetError: [Errno 104] Connection reset by peer
* [ERROR] (nc) No data received, disconnecting!

What InspIRCd sees:
* \<clank.techtronix.net\>	LINK: Server relay.techtronix.net split: The TLS connection was non-properly terminated.

Edit by @GLolol: removed quote

**Comment by Techman-** [comment]
https://pastebin.com/MZQgYAPS

**Comment by GLolol** [comment]
This seems to be specifically related to OpenSSL 1.0.2, which Python's `ssl` module uses as a backend. This has hit numerous other projects as well:

https://github.com/websocket-client/websocket-client/issues/149
https://github.com/tornadoweb/tornado/issues/438
https://github.com/excon/excon/issues/467

Unfortunately I don't see a fix other than to switch to some other OpenSSL version, and for Ubuntu I don't see any official alternative versions.

**Comment by GLolol** [comment]
Possibly relevant: https://bugs.python.org/issue32533

**Comment by jlu5** [comment]
FWIW This might be fixed by OpenSSL 1.1.1 (Debian 10, Ubuntu 18.04), since I don't see the issue anymore after upgrading.
