### ISSUE TITLE
MLOCK support

### ISSUE THREAD

**Issue by cooper** [jlu5/PyLink#466]
PyLink does not properly propagate MLOCK messages. Consequently, remote relay users can evade the mode lock.

Although it is discouraged to use services of multiple networks in a relayed channel, the case when multiple servers have different MLOCKs set should be considered.

**Comment by GLolol** [comment]
In a relay context it may be best to just silently drop mlock requests from networks that aren't in the claim list. (Now that I think about it, we could be doing this for regular MODEs too when mode fighting occurs)
