### ISSUE TITLE
[RFC] Relay server bridging & metadata proposal

### ISSUE THREAD

**Issue by jlu5** [jlu5/PyLink#514]
The situation today is that many networks run multiple PyLink relay instances linked to one IRCd, with each relay instance administered by a different person. While this is a functional setup, lack of communication between relay instances on one network causes problems such as:

- Doubled or wrong network tags, which can lead to confusion
- Incorrect network info in /whois, showing the details of the network in the middle instead of the target's actual network
- Lack of services account metadata, which will break exttargets etc.
    - Technically, this is because relay users' services accounts are never actually sent through S2S to prevent clashes with services. Instead, they're only displayed by Relay on `/WHOIS` by looking up the source user's information.

----
My proposal to work around these problems is to send user metadata through the S2S protocol, using the abstractions IRCds already have to set & broadcast metadata. This metadata command would probably take the following args, with the command name wrapped depending on the protocol:

`<source network> <source server name> <services account or *> :<source network's full netname>`
- I'm omitting the "original nick" slot because the PyLink server would have to send out a new metadata command for every nick change, which is inefficient...

Checklist:

- [ ] Implement incoming / outgoing METADATA support
    - [ ] InspIRCd: via `METADATA pylinkrelayinfo :text`
    - [ ] TS6: likely via `ENCAP * PYLINKRELAYINFO`
    - [ ] ngIRCd: via `METADATA pylinkrelayinfo :text`
    - [ ] UnrealIRCd: via `MD`? https://github.com/unrealircd/unrealircd/blob/unreal40/src/modules/m_md.c
    - [ ] P10: https://github.com/evilnet/nefarious2/blob/master/doc/readme.xquery (requires specific target server) or https://github.com/evilnet/nefarious2/blob/master/ircd/m_mark.c ?
- [ ] Add attributes to `classes.User` to store this info
    - Possible names: `.relay_services_account`, etc.
    - [ ] Consider reusing these attributes for relay users on the current instance as well, instead of looking them up on every call..
- [ ] Implement support for this in relay `/WHOIS` handlers
- [ ] Add support to exttarget handlers (`$account`, `$network`)

**Comment by GLolol** [comment]
After further investigation, it appears that IRCds' metadata commands do not store data persistently after disconnect. Therefore, we would need to rebroadcast this metadata every time a pre-defined bridge server connects.
