### ISSUE TITLE
Let the topic command echo back the current topic of a specified relay endpoint channel.

### ISSUE THREAD

**Issue by MrBenC** [jlu5/PyLink#631]
<+Ben> Feature request - Change the PyLink topic command so if you specify no topic change, to just echo back what the topic is and make that work for everyone.
<+Ben> PyLink: remote ovd topic #chat
<@PyLink> Error: You are missing one of the following permissions: networks.remote, networks.remote.ovd, networks.remote.ovd.pylink, networks.remote.ovd.pylink.topic
<+Ben> So that command will work for anyone to just echo back.
<+Ben> Maybe make it reply in PM or PN (private notice).

**Comment by jlu5** [comment]
#291 #391 are probably a more complete solution. remote is restricted by default so this wouldn't work out of the box anyways
