### ISSUE TITLE
Network Bridging

### ISSUE THREAD

**Issue by Ronsor** [jlu5/PyLink#635]
PyLink should be able to bridge entire networks (all the channels) just as janus could (albeit poorly). Not high priority.

**Comment by jlu5** [comment]
I'm not convinced there's a practical use for this sort of bridging. If you want a completely integrated network, you should be linking with S2S: only that will give a consistent experience.

**Comment by Ronsor** [comment]
yeah it's probably not much more useful than an interesting hack
