### ISSUE TITLE
Clientbot - incorrect network name labels for mode lines when netsplits end

### ISSUE THREAD

**Issue by MrBenC** [jlu5/PyLink#643]
Basically, I think the title explains it.  Here's an excerpt of what I'm talking about.  Shouldn't it say, in this particular example, "NoTrollPlzNet" for both lines?

`<@PyLink> [ChatLounge] - PyLink (~PyLink@enigma.overdrivenetworks.com) sets mode +v mad on #overdrive`
`<@PyLink> [NoTrollPlzNet] - Netjoin gained users: mad`

**Comment by jlu5** [comment]
This is not really a bug. Service bot clients are always defined as local to each network, meaning that Relay doesn't see them as being 'remote' when an event pops out of them.
