### ISSUE TITLE
Add XMPP support?

### ISSUE THREAD

**Issue by poVoq** [jlu5/PyLink#655]
Would be really cool if this could also natively bridge to XMPP MUCs.
Seems like it was mentioned before: https://github.com/jlu5/PyLink/issues/371

There is an easy to use Python library for it:
http://sleekxmpp.com/getting_started/component.html
or:
https://lab.louiz.org/poezio/slixmpp

Thanks for considering!

**Comment by jlu5** [comment]
I'd be happy to help out if anyone wants to work on a protocol module! I personally don't have plans to add new transports right now.

**Comment by poVoq** [comment]
Understandable, but is there somewhere a documentation on how to write a protocol module?

**Comment by jlu5** [comment]
See https://github.com/jlu5/PyLink/tree/devel/docs/technical and especially the [Protocol Module Spec doc](https://github.com/jlu5/PyLink/blob/devel/docs/technical/pmodule-spec.md).

**Comment by jlu5** [comment]
There's also https://github.com/PyLink/pylink-discord which is a wrapper around disco-py for Discord.

**Comment by jlu5** [comment]
Per fc971aa6792f06543c30def82394c2345ddbd915 I'm going to mark this as wontfix. PyLink's internals are very coupled to IRC, largely because of the amount of state it has to track, and the last attempt to extend it outside IRC ended up as a jumbled mess, hard to maintain...
