### ISSUE TITLE
Q: UnrealIRCD 5.0.3.1 supported?

### ISSUE THREAD

**Issue by westor7** [jlu5/PyLink#657]
Hello,

I wanna ask if PyLink has full support for the latest UnrealIRCD stable version.

- Thanks!

**Comment by jlu5** [comment]
Yes, PyLink works fine with Unreal 5 in my testing. There weren't any breaking changes at the S2S level, so not much needs to be changed in PyLink.

The next release, PyLink 2.1 will be merged into `master` soon. It officially supports Unreal 5.

**Comment by jlu5** [comment]
PyLink 3.0-rc1 has been pushed to master with official support for Unreal 5.
