### ISSUE TITLE
Configurable files location

### ISSUE THREAD

**Issue by Celelibi** [jlu5/PyLink#658]
There is currently not much choice regarding the location and names of the files generated by pylink. Namely logs, database and pid files have a fixed location and a hardcoded name patterns. I especially find it pretty dubious to put the pid file and `pylinkrelay.db` in the current directory, which will usually be the home directory.

I think a first fix could just have global configurations `data_dir`, `log_dir` and `pid_dir`.
In a more sophisticated solution some of those could be overriden on a per-plugin basis when it make sens. Choosing the file names could also become handy in some setups, I guess.

**Comment by jlu5** [comment]
This will be included in the next feature release (3.1)
