### ISSUE TITLE
Hub mask problem

### ISSUE THREAD

**Issue by SlaSerX** [jlu5/PyLink#662]
Hello i use charybdis and when try to relay i take this error 

No matching hub_mask for magicnet.relay

**Comment by jlu5** [comment]
Did you set the right value in your `connect` block? It should match your relay server suffix (e.g. `*.relay` by default)

https://github.com/charybdis-ircd/charybdis/blob/9dd128b4da6e54ca9f97cfcd48e345a57790ffbe/doc/reference.conf#L581-L584

**Comment by jlu5** [comment]
Solved per discussion on IRC
