### ISSUE TITLE
User with ident containing / (slash) joining a channel linked to Solanum causes a server connect and disconnect loop

### ISSUE THREAD

**Issue by Semisol** [jlu5/PyLink#673]
How to reproduce:
- Create user with ident with `/`
- Make it join a channel linked to Solanum
- Eventually (PyLink restart I believe), the server will connect, get disconnected, and reconnect again, forever or until the user is removed from all channels that are linked.

[logs](https://paste.semisol.dev/raw/goqzjkxytq)

**Comment by jlu5** [comment]
By the way, what source IRCd are you using that allows "/" in nicks? Unreal, InspIRCd, solanum, and Nefarious all disallow this for regular users.

**Comment by Juliaria08** [comment]
@jlu5 I think @Semisol meant a IDENT with `/` not a nick

**Comment by jlu5** [comment]
Yeah that's a typo in my reply, the commit above does address it for idents
